name: peermatching
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.7
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_animation_progress_bar: ^2.3.1
  flutter_rating_bar: ^4.0.0
  
  url_launcher: ^6.1.10

  #DI
  get_it: ^7.2.0

  #STATE_MANAGEMENT
  stacked: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: '#f7f6f1'
  color_dark: '#272727'
  image: assets/images/logo-w-text.png
  image_dark: assets/images/logo-w-text.png

  android_12:
    image: assets/images/logo-w-text.png
    icon_background_color: '#f7f6f1'
    image_dark: assets/images/logo-w-text.png
    icon_background_color_dark: '#272727'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
